FROM python:3.11-slim

WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code and .env
COPY . .

ARG google_api_key="AIzaSyDd0dQsCItbwFy0_hJkTiOEfFVzTmbXhhc"
ARG backend_url="https://knewbit-backend-prod-112842299929.asia-south1.run.app"
ENV GOOGLE_API_KEY=${google_api_key}
ENV BACKEND_API_URL=${backend_url}

EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]